In [45]:
a='saket maheshwari'
out=a.title()
print(out)

Saket Maheshwari


In [47]:
a='Shenanigam'
#out=a[:2]
out1=a[4:6:]
#print(out)
print(out1)

an


In [49]:
def add(a:int,b:int)->int:
    return a+b

add(10,20)


30

In [29]:
#scope of the variable
''' 
local
non local
globla
'''
def add():
    a=0  #local variable
    print(a)

a=25 #gloabal variable
print(a)
add()


25
0


In [9]:
n=(input())
sum=0
if n>="100000" and n<="999999":
    for x in n:
        sum=sum+int(x)
print(sum)

15


In [30]:
n=int(input("Enter The Number"))
rev=0
temp=n

while n>0:
    rev=(rev*10)+(n%10)
    n=n//10
if temp==rev:
    print("Numner Is Palindrome")
else:
    print("Numnber is not palindrome")

Numnber is not palindrome


In [ ]:
def add(num1,num2):
    return num1+num2
num1=int(input(""))
num2=int(input(""))
add(num1,num2)

90

In [ ]:
def my_func(ls):
    t=ls.copy()
    ls.sort()
    if t==ls:
        return 0
    elif t==ls[::-1]:
        return 1
    else:
        return -1

In [ ]:
ls=['saket','','manan']
my_func(ls)

-1

In [ ]:
def apna_function(x):
    return x[-1]

ls=['ramesh','zoya','saket','satish']
ls.sort()
print(ls)

['ramesh', 'saket', 'satish', 'zoya']


In [ ]:
def ascii_value(z):
    return sum(list(map(ord,z)))

ls=['ramesh','zoya','saket','satish']
ls.sort(key=ascii_value)
print(ls)


['zoya', 'saket', 'ramesh', 'satish']


In [ ]:
def my(r):
    for i in range(10):
        print(i)
my(1)

0
1
2
3
4
5
6
7
8
9


In [ ]:
def fact(y):
    facto=1
    for i in range(y+1):
        facto*=i
    print(i)
fact(y)
y=int(input("Enter The Number"))


10


In [ ]:
a=int(input("Enter The Notes"))
while a>10:
    a=a%10
    print(a)
    

5


In [ ]:
def prime(x):
    for i in range(x,2):
        if x%i==0:
            return 1
    return 0
ls=[2,85,32,25,14,78]
ls.sort(key=prime)
ls.sort()
print(ls)


[2, 14, 25, 32, 78, 85]


In [ ]:
#filter 
ls=[2,45,96,54,52,23]
out=list(filter(lambda(x:x%2==0,ls)))

print(out)

SyntaxError: invalid syntax (1756640198.py, line 3)

In [ ]:
import math
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [11]:
# Where the value of n=4
#  4 4 4 4 4 4 4
#  4 3 3 3 3 3 4
#  4 3 2 2 2 3 4
#  4 3 2 1 2 3 4
#  4 3 2 2 2 3 4 
#  4 3 3 3 3 3 4
#  4 4 4 4 4 4 4

n=4
# for j in range(n):
#     print(end="")
    # for j in range(n):
    #     print(n,end="")
for x in range(n):
    print(n)
    for x in range(n-1):
        print(n-1,end=" ")
    #print(end="")

4
3 3 3 4
3 3 3 4
3 3 3 4
3 3 3 

In [ ]:
#modules in python
# modules is just file which contains a a function
'''
1. Math
2. Random
3. Numpy
'''
ls=[20,54,32,1,78]
out=max(ls)
print(out)

78


In [ ]:
import math
a=9
out=math.factorial(a)
out1=math.sqrt(a)
print(out,out1)

362880 3.0


In [ ]:
from math import sqrt,factorial
a=9
out=sqrt(a)
print(out)

3.0


In [ ]:
value=154
out=log(10,value)
print(out)

0.4571385269519278


In [ ]:
a=65536
out=int(log(a,256))+1
print(out)

3


In [ ]:
# Code you have previously used to load data
import pandas as pd

# Path of the file to read
iowa_file_path = '../input/home-data-for-ml-course/train.csv'

home_data = pd.read_csv(iowa_file_path)

# Set up code checking
from learntools.core import binder
binder.bind(globals())
from learntools.machine_learning.ex3 import *

print("Setup Complete")

ModuleNotFoundError: No module named 'pandas'

In [ ]:

n=int(input("Enter The Number"))
for x in range(2,n):
    if n%x==0:
        print("Not prime number")
        break
else:
    print("a prime")

Not prime number


In [ ]:
x=int(input("Enter The Number"))
lambda x:x<10 

<function __main__.<lambda>(x)>

In [ ]:
'''
Random Variable Generator
'''
import random
out=random.randrange(1,10)
print(out )


6


In [ ]:
#randint(): return the random within the inclusive range

out=random.randint(1,5)
print(out)

1


In [ ]:
# getranbits(): return random integer with k bits

out=random.getrandbits(4)
print(out)

15


In [ ]:
# Choice(): return any random element
ls=['a','b','c','d','e']
out=random.choices(ls,weights=[1,1,1,10,1])
print(out)

['d']


In [ ]:
# sample()
ls=['a','a','c','d','e']
out=random.sample(ls,k=1)
print(out)

['a']


In [ ]:
# shuffle
# sample()
ls=['a','a','c','d','e']
print("Before Shuffle", ls)
random.shuffle(ls)
print("After Shuffle" ,ls)



Before Shuffle ['a', 'a', 'c', 'd', 'e']
After Shuffle ['c', 'e', 'a', 'd', 'a']


In [ ]:

out=random.random()
out1=out*10000
s=int(out1)

print("OTP IS", s)

OTP IS 7191


In [ ]:

out=random.triangular(4,5,9)
out1=eval(out[::4])
print(out1)

TypeError: 'float' object is not subscriptable

In [ ]:
from datetime import datetime
import random
import time

odds=[1,3,5,7,9,11,13,15,17,
    19,21,23,25,27,29,31,35,37,39
    ]
right_tgis_minute=datetime.today().minute
if right_tgis_minute in odds:
    print("This Semms a little odd")
else:
    print("not an odd")
wait=random.randint(1,10)
time.sleep(wait)

This Semms a little odd


In [1]:
lst=[[2,4,6],[1,5,8],[1,2,4]]
for x in lst:
    print(*x,sep='\t')

2	4	6
1	5	8
1	2	4


In [ ]:
#matrics:
def matrics(arr):
    ln=len(arr[0])
    for x in arr:
        if len(arr)!=ln:
            return False
    return True

mat=[[1,2,3],[4,5,6],['s',8,9]]
if matrics(mat):
    print(f'Dimension of matrice {dim}')
    for x in mat:
        print(*x,sep="\t")
    else:
        print("Invalid Martice")

Dimension of matrice [[1, 2, 3], [4, 5, 6], ['s', 8, 9]]
1	2	3
4	5	6
s	8	9
Invalid Martice


In [32]:
#Enter Two List By The User and retrive  not common elemnets of the list

ls1=[2,4,5,6]
ls2=[3,5,4,6]

list(set(ls1).intersection(ls2))
  

#uncommon elements


# Enter List from the user and square each elements of the list








NameError: name 'eachlist' is not defined

In [15]:
#Enter List from the user and retrive even elements of the list
nums = input('Enter')
for n in nums.split(','):
    for n in nums:
        if n%2==0:
            print(nums)
        else:
            print("exit")


TypeError: not all arguments converted during string formatting

In [1]:
list_one = [4,5,6,7]
list_two = [4,5,6]

non_common = set(list_one).difference(list_two)

print(non_common)


{7}


In [9]:
ls=[1,2,5,4]
a=[]
for x in ls:
    if x%2==0:
        a.append(x)
print(a)
              

[2, 4]


In [10]:
i=3.5
k=1.2
print(i%k)

1.1


In [13]:
a=10
b=5
a=a^b
b=a^b
a=a^b

print(a)
print(b)

5
10


In [60]:
import random
a=1000
b=9999
out=random.randint(a,b)
print(out)


9193


In [1]:
import calendar
month=1
Year=2005
for i in range(12):
    print(calendar.month(Year,month))
    month+=1


    January 2005
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31

   February 2005
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28

     March 2005
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31

     April 2005
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30

      May 2005
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31

     June 2005
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30

     July 2005
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31

    August 2005
Mo Tu We Th Fr

In [16]:
'''NumPy is a python package. It Stands For 'Numerical Python'. It is a library consisting of multidimensional array
objects and a collection of routines for processing of array

'''

# First Function
import numpy as np
a=np.array([1,2,2])
print(a)

[1 2 2]


In [13]:
# Example 2
import numpy as np
ls=[4,8,9,6]
arr=np.array(ls)
print(ls)
print(arr)

[4, 8, 9, 6]
[4 8 9 6]


In [3]:
# Multilication Of Matrices
import numpy as np
ls1=[[2,5,6,7],[8,9,2,3]]
ls2=[[2,8,3,9],[7,2,6,4]]
arr=np.array()
arr.shape=1,6
print(arr)

TypeError: array() missing required argument 'object' (pos 0)

In [39]:
import numpy as np
ls=[[[0,5,4,7,4,7,9,5,]]]
out=np.array(ls,ndmin=2)
print(out,out.ndim)

[[[0 5 4 7 4 7 9 5]]] 3


In [58]:
# Matrix Of Addition

m1=[[4,5,8],[25,53,54],[32,85,96]]
m2=[[78,58,58],[598,59,96],[36,74,25]]




arr1=np.array(m1)
arr2=np.array(m2)

if arr1.shape==arr2.shape:
    out=np.dot(arr1,arr2)
    print(out,)
else:
    print("Shape Is Not Valid")

[[ 3590  1119   912]
 [35588  8573  7888]
 [56782 13975 12416]]


In [2]:
# Matrix Of Addition

r1,c1=map(int,input("Enter The Shape").split('x'))

m1=eval(str([[0]*c1]*r1))
for i in range(r1):
    for j in range(c1):
        m1[i][j]=int(input(f'Enter The Element {i+1}*{j+1}'))


r2,c2=map(int,input("Enter The Shape").split('x'))

m1=eval(str([[0]*c2]*r2))
for i in range(r1):
    for j in range(c1):
        m1[i][j]=int(input(f'Enter The Element {i+1}*{j+1}'))




arr1=np.array(m1)
arr2=np.array(m2)

if arr1.shape==arr2.shape:
    out=np.add(arr1,arr2)
    print("Matrx1")
    print(arr1)
    print('Matrix2')
    print(arr2)
    print('Multiplication')
    print(out)
else:
    print("Shape Is Not Valid")

ValueError: invalid literal for int() with base 10: ''

In [6]:
import numpy as np

out=np.zeros((3,3))
print(out)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
out=np.ones((3,3))
print(out)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
out=np.eye(3)
print(out)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
ls=list(map(eval,input().split()))

arr=np.array(ls,dtype=float)
#out=np.flip(arr)
print(arr[::-1])

[9. 8. 7. 6. 5. 4.]


In [37]:
import numpy as np
ls=[1,2,3,4,5,6,7,8,9]
ar=np.array(ls)
print(ar.reshape(3,3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
r,c=list(map(eval,input().split()))
out=np.eye(r,c)
print(out)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [2]:
import numpy as np
r=list(map(eval,input().split()))
c=list(map(eval,input().split()))

out=np.array(r)
out1=np.array(c)
print(*out+out1)

99 590 99


In [46]:
ls=[45,45,85]
ls2=[85,96,49]
ls1=np.array(ls)
ls2=np.array(ls2)
print(*ls+ls2)
np.eye(*(5,5))
print(ls1.ndim)


130 141 134
1


In [4]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr.shape


(2, 2, 3)

In [31]:
arr=np.array([[2,6,4]])
count=0
for x in arr:
    print(tuple(a))
    count+=1
print("Count", count)

(2, 6, 4)
Count 1


In [70]:
space=np.linspace(2,5,5)
print(*space)

2.0 2.75 3.5 4.25 5.0


In [1]:
arr=np.arange(99)
print(arr)
arr.ravel()
arr.shape

NameError: name 'np' is not defined

In [6]:
import numpy as np
ls=[32,35,78,45]
ls1=[1.8*c +32 for c in ls]
print(ls1)

[89.6, 95.0, 172.4, 113.0]


In [19]:
ls=[10,25,45,78]
ls1=[i for i in ls:i+1]
print(ls1)

SyntaxError: invalid syntax (4245797203.py, line 2)

In [73]:
st='saketmaheshwari.cs.it@gmail.com'
ls=[i for i in st if i.isalpha()]
print(*ls)

s a k e t m a h e s h w a r i c s i t g m a i l c o m


In [93]:
ls=[45,85,78,54,58,87]
out=[x+2 for x in ls ]
print(out)

[47, 87, 80, 56, 60, 89]


In [115]:
ls=[78,87,85,74,4]
out=['even'if x%2==0 else 'odd' for x in ls]
print(out)

['even', 'odd', 'odd', 'even', 'even']


In [122]:
sam=[45,2,87,54,5,78]
out=["pass" if x>33 else 'fail' for x in sam]
print(out)

['pass', 'fail', 'pass', 'pass', 'fail', 'pass']


In [1]:
ls=['saket','rohn','sidd','aet','div']
out=[x if x<='a' and x>'z' for x in ls]
print(out)

SyntaxError: expected 'else' after 'if' expression (3483720217.py, line 2)

In [16]:
'''
Dictionary object in python:
Unorderd collection of items and each items is the pair of key and value
'''
info={'name':'yash','name':'saket','Marks':[25,30,36,12],'College':'GLAU'}
print(type(info))
out=info
info['adress']='chaumuhan'
print(out)

<class 'dict'>
{'name': 'saket', 'Marks': [25, 30, 36, 12], 'College': 'GLAU', 'adress': 'chaumuhan'}


In [21]:
info={'name':'yash','name':'saket','Marks':[25,30,36,12],'College':'GLAU'}
del info['name']
print(info)

{'Marks': [25, 30, 36, 12], 'College': 'GLAU'}


In [23]:
'''
Method in dict
get(key): Returns The Value of the given key is found
return default  value if key is not found
'''

info={'name':'yash','name':'saket','Marks':[25,30,36,12],'College':'GLAU'}
out=info.get('Mobile',"N/A")
print(out)

N/A


In [28]:
# Clear(): Remove All items from dict object
info={'name':'yash','name':'saket','Marks':[25,30,36,12],'College':'GLAU'}
info.clear()
print(*info)

In [1]:
# copy(): Returns the shalow copy of the dict object
info={'name':'yash','name':'saket','Marks':[25,30,36,12],'College':'GLAU'}
var=info.copy()
print(info,id(info))
print(var,id(var))

{'name': 'saket', 'Marks': [25, 30, 36, 12], 'College': 'GLAU'} 1767147391360
{'name': 'saket', 'Marks': [25, 30, 36, 12], 'College': 'GLAU'} 1767168980864


In [45]:
ls={'name':'yash','name':'saket','Marks':[70,80,76,82],'College':'GLAU'}
ls['contact']=[7217572227]
for i in ls:
    print(i,':',ls[i])

name : saket
Marks : [70, 80, 76, 82]
College : GLAU
contact : [7217572227]


In [59]:
ls=['Name','Last Name','Mobile Number','University','Branch']
output=['Saket','Maheshwari','7217572227','GLA University','B.Tech CS']
out=dict.fromkeys(ls,output)
for x in ls:
    ls[i]+ls[out]
    print(x)

TypeError: list indices must be integers or slices, not str

In [33]:
import math
ls=[1,2,3,4,5]
output=[6,7,8,9,10]
out=dict.fromkeys(ls,output)
for x in ls:
    out1=tuple(ls)+tuple(output)
print(out)

{1: [6, 7, 8, 9, 10], 2: [6, 7, 8, 9, 10], 3: [6, 7, 8, 9, 10], 4: [6, 7, 8, 9, 10], 5: [6, 7, 8, 9, 10]}


In [3]:
for x in range(1,100):
    if x==50:
        continue
    print(x,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [19]:
s1=list(map(eval,input("Enter The Numbers").split()))
s2=out
for x in s1:
    out=x*x
    print(out)
    
print(s2)

25
